services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      PGPASSWORD: example
      POSTGRES_PASSWORD: example
      PGDATABASE: net_be_genai_plgrnd_db
      POSTGRES_DB: net_be_genai_plgrnd_db
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    expose:
      - "45432"   
    ports:
      - "45432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./
    restart: always
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3002"  
    ports: 
      - 3002:8080
    environment:
      ConnectionStrings__SportsHubDb: "Server=db;Database=net_be_genai_plgrnd_db;User ID=postgres;Password=example;Port=5432"

  angular_frontend:
    build: ../sports_hub_angular_skeleton
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: always
    environment:
      REACT_APP_API_URL: "http://localhost:3002"
      NG_APP_API_URL: "http://localhost:3002/"

volumes:
  pg-db-data:
