version: '3.9'
services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      PGPASSWORD: example
      POSTGRES_PASSWORD: example
      PGDATABASE: net_be_genai_plgrnd_db
      POSTGRES_DB: net_be_genai_plgrnd_db
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    expose:
      - "45432"   
    ports:
      - "45432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./
    restart: always
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "30022"  
    ports: 
      - "30022:8080"
    environment:
      ConnectionStrings__SportsHubDb: "Server=db;Database=net_be_genai_plgrnd_db;User ID=postgres;Password=example;Port=5432"

volumes:
  pg-db-data:
